version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/daniel-shuy/renovate
  renovate: daniel-shuy/renovate@3.1.0

jobs:
  run_tests_java:
    docker:
      - image: cimg/openjdk:17.0.0
    steps:
      - checkout
      - run: |
          ./gradlew clean test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results

workflows:
  version: 2
  run_tests:
    jobs:
      - renovate/validate-config
      - run_tests_java
